### ISSUE TITLE
Implement year filters in store search

### ISSUE THREAD

**Issue by leejunkit** [22media/JPMobilePM#16]

**Comment by wirelessed** [comment]
@leejunkit after filtering, show filtered pills like this: 
![image](https://user-images.githubusercontent.com/180234/69109361-7e70ce80-0ab2-11ea-937c-3afec3d16f15.png)

**Comment by leejunkit** [comment]
Multiple years filter requires server-side upgrade of Scout Extended.

**Comment by leejunkit** [comment]
<img width="526" alt="Screenshot 2019-11-20 at 3 47 52 PM" src="https://user-images.githubusercontent.com/828652/69319215-baa25b80-0c79-11ea-96a8-e055bed6ae91.png">

Need @wirelessed help for the margin bottom

**Comment by leejunkit** [comment]
Works as of https://github.com/22media/JPMobileRN/commit/3e8c4a0ab453e0d28f584bcf5099fc0ea2cecd8f

**Comment by leejunkit** [comment]
Original issue was to implement the year filter pills and modal in the UI. This has been done, so I'm creating a new issue #45 to track multiple year filtering enhancement, and closing this issue.
