### ISSUE TITLE
Update sermon notes webview to be dark-mode aware and Lato font

### ISSUE THREAD

**Issue by leejunkit** [22media/JPMobilePM#18]

**Comment by wirelessed** [comment]
@leejunkit 
I finished styling the webview branch for light mode and dark mode.
A couple of issues I realised:
- In dark mode, when the webview is loading, it is still white :(
- Praise Reports List View is now in React Native and not Webview? If so, then we need to style the Praise Reports in React Native side

**Comment by leejunkit** [comment]
Fixed white flash when webview is loading by updating `react-native-webview`. Fixed in 22media/JPMobileRN@d3499e4

**Comment by leejunkit** [comment]
> In dark mode, share icon in sermon notes is still the wrong color

@shanosh can help me out with this?

**Comment by leejunkit** [comment]
> > In dark mode, share icon in sermon notes is still the wrong color
> 
> @shanosh can help me out with this?

Implemented, 22media/JPMobileRN@8f09c13755ea50eff1996d2a61421970e19c865e
