### ISSUE TITLE
Today Hero Image not working on Android sometimes

### ISSUE THREAD

**Issue by wirelessed** [22media/JPMobilePM#29]
For sermon series, whenever there is HeroImage, use it instead of the default image path. 

Sample logic from jpcom
`
    if(isset($sku->sku_code) && str_contains($sku->sku_code, 'DJVA') && isset($product->productHeroImagePath) ){
        $imagePath = $product->productHeroImagePath;
    }
`

**Comment by shanosh** [comment]
Fixed
